parameters: 
        caxy_annotation.twig.extension.class: Caxy\AnnotationBundle\Twig\Extension\AnnotationExtension

services:
    annotation_extension:
        class: %caxy_annotation.twig.extension.class%
        arguments: [@service_container]
        tags: 
            - { name: twig.extension }