<?php

namespace Caxy\AnnotationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnotationRepository extends EntityRepository
{
}
